### ISSUE TITLE
Create boilerplate SQL queries

### ISSUE THREAD

**Issue by JamesRichards07** [ravenfire/magpie#7]
These are my current thoughts when creating SQL queries which could be common for other users of Magpie.
- [x] Create SQL query which counts the number of results grouped by column information on a given table. 
                            BGG Table
     i.e.    number_of_players.     count
               2-4 players                  538
               3-7 players                  124

- [x]  Create SQL query which searches for a given input using WHERE.
- [x]  Create SQL query to join sources with the primary entity into one table. (The user of the framework can then write specific SQL queries based on their need. I think this boilerplate query could become a subquery in that case.)
- [x]  Build a small CLI to handle to SELECT, JOIN, WHERE, and GROUP BY.
- [x]  Document usage in README.md

**Comment by electricjones** [comment]
Yeah, I think those are great places to start.

I have some suggestions for when you start building the CLI part. Some tools that will make things easier. But I want to give you the freedom to explore. So, let me know how/when you'd like my thoughts on that architecture.

**Comment by electricjones** [comment]
I'm also adding a checkbox to document the queries in the README.md file before merging into master.

**Comment by JamesRichards07** [comment]
So I have read through Laravel query builder and it appears most of these queries need to use the `use Illuminate\Support\Facades\DB;` instead of just calling the model and using `where` like I did to check if a particular game already exists.

**Comment by electricjones** [comment]
That is correct. And, since we don't use the full Laravel Framework, just some packages, this link will be helpful: https://github.com/illuminate/database. It shows you a couple minor differences. All the setup is already done. You should be good to just use the DB facade.

You may not be heading in this direction, but I wanted to guide you away from in it case. It'll make things much harder. For this, we do not want to use a query builder. That is, we don't want to do things like `Game::select('*')->where('something', true)->get()`. We want to write all the sql our selves and not use models at all.

More like this: `$users = DB::select('select * from users where active = ?', [1]);`. And we will likely end up doing something even more like this

```php
$sql = "select * from {$table} where {$column} = '{$value}'";
$results = DB::select($sql);
```

At least at first. That's kinda insecure, but one step at a time, lol.

So, note that doesn't return a model, it returns something like an array of arrays, where each element of the first array is a row in the database.

**EDIT**: I was wrong. The `DB` facade is not setup when using the illuminate package. You have to use the `Capsule`. See link above.

**Comment by JamesRichards07** [comment]
That makes sense. Since this is all new it's hard for me to know how to write the sql in php. All I can find are example which use the query builder (which we don't want). 

ie. $users = DB::table('users')
            ->join('contacts', 'users.id', '=', 'contacts.user_id')
            ->join('orders', 'users.id', '=', 'orders.user_id')
            ->select('users.*', 'contacts.phone', 'orders.price')
            ->get();
            
I guess I'm struggling to translate the above into a single string like you mentioned.

**Comment by electricjones** [comment]
You just write the sql query as a string in a variable, and then use the
snippet I showed above to perform the query.

I can be more specific in a bit.I am about to work on my taxes.
